In [1]:
## Numpy helps in doing mathematical operations, arrays,matrices etc.

!pip install numpy

In [6]:
import numpy as np

##create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
##identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## attributes of numpy array
arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size(number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size(in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size(number of elements): 6
Data type: int64
Item size(in bytes): 8


In [14]:
## Numpy vectorised operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element wise addition
print("Addition:",arr1+arr2)

### Element wise substraction
print("substraction:",arr1-arr2)

### Element wise multiplication
print("multiplication:",arr1*arr2)

### Element wise division
print("division:",arr1/arr2)


Addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [15]:
## Universal functions
arr=np.array([2,3,4,5,6])
##square root
print(np.sqrt(arr))

##Exponential
print(np.exp(arr))

##Sine
print(np.sin(arr))

## natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [17]:
## Universal functions
### array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)



Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
arr[0][1]

np.int64(2)

In [22]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [23]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [26]:
### statistical concept--Normalisation
##to have a mean of 0 and standard deviation of 1

data=np.array([1,2,3,4,5])

## calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

##normalise the data
normalized_data=(data-mean)/std_dev
print("normalized data:",normalized_data)


normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
